{% set version = "0.73.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lsa
  version: {{ version|replace("-", "_") }}

source:
  fn: lsa_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lsa_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lsa/lsa_{{ version }}.tar.gz

  sha256: cb0017bbda9b0eb1d05b451e0f557d02f789f65b2f8bf005606b63a3708e63a8

build:
  noarch: generic
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-snowballc

  run:
    - r-base
    - r-snowballc

test:
  commands:
    - $R -e "library('lsa')"  # [not win]
    - "\"%R%\" -e \"library('lsa')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lsa
  license: GPL (>= 2)
  summary: The basic idea of latent semantic analysis (LSA) is,  that text do have a higher order (=latent semantic) structure which,  however, is obscured by word usage (e.g. through the use of synonyms  or polysemy). By using conceptual indices that are derived statistically  via a truncated singular value decomposition
    (a two-mode factor analysis)  over a given document-term matrix, this variability problem can be overcome.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
