appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZQ9h7PNR9zABw+3b/PihAnnB/gbnRWAu4eTjqPMoZX7CWXolLONETf/A7gT4IttKZPXcstJfQSbjg5RN7orQ+2aNc6onGKDYqlJpAUcEdr4dXu2/YXzPu7If2J+02S8rWQU+FsWBwCYpGWlzNOg7DdEZRPmHuKPHJfo2Lwq6k/4oBh/d9sgJ8B5mUYDGjKH60AAgpDWCJ1koZ1dDJ8izLyXalGujSSMjJWXEsDFW4qOICqS+1I5hK7O0PGruMec/67OXM1KZWF8b2jHIAzuSP1nUzLKXYwGyCEJPRsiMhyx5a+0ruRxuTCAY5t7C+4dHPE8RfixyYSi4lRmixG7ep6z4TB3O924Sh/COHJ62SsuUM7VhlpnQQu6PC9UZPMDwXJprb7WM1csURbsNKU4/wBF0eWjS+mQnWqkQM3xeX5m4qh48x0CQFuBlWE/s9mbsXyUSTLOHgOmbimPT0CmP0znRik0VcymsiCi/twHz5Ih0GfXUE3XsDJlP0WX+PaH1AchgGLZoeNStSSuoUeicSJXnPZhBSg54BwwJg5oqoKZcw7aAFRFVN5pQKqmCrIXMxcGBKudeSuQz8L2Hhl6DTBsroZg71HPBndYTmnrAfB9oavtqcyZIiQXxGqvCqWJ/YhsWcMd5yW40fhnZ+9mIrLEewoy3yMQOn0tHDa6YlKg=}
bot:
  automerge: true
