travis:
  secure:
    BINSTAR_TOKEN: Lb/RlqdxWh6WnWsr9YVgHBI9FsBR9T4fU/tdmJKtymftcJPTtmZ1xTNKR2bWilqJ2ISCr/ftXk3uPBDwZGTYVaZwVypBAmqoAD05Sxhol/9OojaGQKRjr7Ky7s2JsdgqNivjwLsRNeEK9CU3N86m7dPsWVkJId0x8xN1HDQiXbuDol1KMlWJuqLE5YlWfI5xV5m7Syn46HZdrv6JMSM8Pbdo7+ZQajpZgmsnnJXnCy122aQ3R4ITMCGn/vyVctdZehvD6w01GrCSkeUqG+Vsa5HW8qBa3xaNprhywuSNqZaP4WPpDeHT9LrjDJ2MxWfoq9ZPnmCLKdyrm7Dpq8F+Lc0koKCvswd75PK6nTp9C3xN3q72uN5LlSIX13SnAaZLfyPxdu1cFFkISxYpyS1CCplm+wUqIq7OhTaZm/MPTasxMZlrwNY/lEZbOQzn2R21wn8yb8rY/XUDlVKa2mmarmpE+KZW6f32v9dmhrwO8kbOyfsvfOPZs8QBtvH5ZE/W5q0cQit/SO6hSqMNSdBjDAwquCB6p4KtD7VUj6PabRX1E/D0e4T0MARjdt7DfY3HABn8Peoc9uoBYLzvDIcyf+ZS4Vx1TfJh8IopW/Kxn692mrBd4vMr8n93vzrCLjEMediGBIHn9jGtoslNNFCRv0w47pqO31/6qG2uMXRePg8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
